#!/usr/bin/python3
import math
from sys import argv


def factorize():
    with open(argv[1]) as f:
        for number in f:
            num = int(number)
            flag = 0
            for x in range(2, int(math.sqrt(num)) + 1, 1):
                if num % x == 0:
                    print("{:d}={}*{}".format(num, num // x, x))
                    flag = 1
                    break
            if flag == 0:
                print("{:d}={}*{}".format(num, num, 1))


if __name__ == '__main__':
    factorize()
